service:
  name: translate-ms

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  
functions:
  translate:
    handler: dist/handlers/translate.handler
    timeout: 45
    events:
      - http:
          method: GET
          path: /translate/{url}
    
custom:
  bundle:
    linting: false