service:
  name: translate-ms

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    REDIS_PORT: ${self:custom.Redis.port}
    REDIS_HOST: ${self:custom.Redis.host}
    REDIS_PASSWORD: ${self:custom.Redis.password}
  
functions:
  translate:
    handler: dist/handlers/translate.handler
    timeout: 45
    events:
      - http:
          method: GET
          path: /translate/{url}
    
custom:
  Redis:
    port: ${file(env.yml):Redis.port}
    host: ${file(env.yml):Redis.host}
    password: ${file(env.yml):Redis.password}
  bundle:
    linting: false